ALL_TRAINING_COLUMNS = [
    'host_since', 'host_response_rate', 'host_acceptance_rate', 'host_is_superhost',
    'host_listings_count', 'host_total_listings_count', 'host_has_profile_pic',
    'host_identity_verified', 'latitude', 'longitude', 'accommodates', 'bedrooms', 'beds',
    'minimum_nights', 'maximum_nights', 'availability_30', 'availability_60',
    'availability_90', 'availability_365', 'number_of_reviews', 'review_scores_rating',
    'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin',
    'review_scores_communication', 'review_scores_location', 'review_scores_value',
    'instant_bookable', 'calculated_host_listings_count', 'reviews_per_month',
    'host_duration_days', 'num_bathrooms', 'is_shared_bath', 'num_amenities',
    'num_host_verifications', 'never_reviewed', 'days_since_last_review',
    'days_since_first_review', 'desc_sentiment', 'col_2_5_years_old',
    'col_5_10_years_old', 'amazon_prime_video', 'and_10_years_old',
    'and_5_10_years_old', 'and_dresser', 'apple_tv', 'chromecast', 'closet',
    'disney', 'espresso_machine', 'every_day_available_at_extra_cost',
    'french_press', 'hbo_max', 'heated', 'nespresso', 'netflix', 'open_24_hours',
    'open_specific_hours', 'pool_cover', 'pour_over_coffee', 'premium_cable',
    'standard_cable', 'stationary_bike', 'tuesday_to_friday_available_at_extra_cost',
    'wardrobe', 'yoga_mat', 'col_55_inch_hdtv_with_apple_tv',
    'col_55_inch_hdtv_with_chromecast', 'col_55_inch_hdtv_with_netflix',
    'air_conditioning', 'arcade_games', 'baby_bath',
    'baby_bath_always_at_the_listing', 'baby_bath_available_upon_request',
    'baby_monitor', 'baby_monitor_available_upon_request', 'baby_safety_gates',
    'babysitter_recommendations', 'backyard', 'baking_sheet', 'barbecue_utensils',
    'bathtub', 'bay_view', 'bbq_grill', 'bbq_grill_charcoal',
    'beach_access_beachfront', 'beach_essentials', 'beach_view', 'bed_linens',
    'bidet', 'bikes', 'blender', 'bluetooth_sound_system', 'board_games',
    'boat_slip', 'body_soap', 'books_and_reading_material',
    'bosch_refrigerator', 'bread_maker', 'breakfast', 'building_staff',
    'canal_view', 'carbon_monoxide_alarm', 'ceiling_fan',
    'central_air_conditioning', 'central_heating', 'changing_table',
    'changing_table_always_at_the_listing',
    'changing_table_available_upon_request', 'children_s_playroom',
    'children_s_bikes', 'children_s_books_and_toys',
    'children_s_books_and_toys_for_ages_0_2_years_old',
    'children_s_books_and_toys_for_ages_0_2_years_old_and_2_5_years_old',
    'children_s_books_and_toys_for_ages_2_5_years_old',
    'children_s_books_and_toys_for_ages_2_5_years_old_and_5_10_years_old',
    'children_s_books_and_toys_for_ages_5_10_years_old',
    'children_s_books_and_toys_for_ages_5_10_years_old_and_10_years_old',
    'children_s_dinnerware', 'city_skyline_view',
    'cleaning_available_during_stay', 'cleaning_products', 'clothing_storage',
    'clothing_storage_closet', 'clothing_storage_closet_and_dresser',
    'clothing_storage_closet_and_wardrobe', 'clothing_storage_dresser',
    'clothing_storage_walk_in_closet',
    'clothing_storage_walk_in_closet_and_closet', 'clothing_storage_wardrobe',
    'clothing_storage_wardrobe_and_dresser', 'coffee', 'coffee_maker',
    'coffee_maker_drip_coffee_maker', 'coffee_maker_espresso_machine',
    'coffee_maker_french_press', 'coffee_maker_nespresso',
    'coffee_maker_pour_over_coffee', 'conditioner', 'cooking_basics',
    'courtyard_view', 'crib', 'crib_always_at_the_listing',
    'crib_available_upon_request', 'dedicated_workspace', 'dining_table',
    'dishes_and_silverware', 'dishwasher', 'double_oven', 'dove_body_soap',
    'dryer', 'dryer_in_building', 'dryer_in_unit',
    'drying_rack_for_clothing', 'electric_stove', 'electrolux_induction_stove',
    'electrolux_refrigerator', 'elevator', 'essentials',
    'ethernet_connection', 'ev_charger', 'ev_charger_level_2',
    'exercise_equipment', 'exercise_equipment_free_weights',
    'exercise_equipment_yoga_mat', 'exterior_security_cameras_on_property',
    'extra_pillows_and_blankets', 'family_fresh_body_soap', 'fire_extinguisher',
    'fire_pit', 'fireplace_guards', 'first_aid_kit',
    'free_driveway_parking_on_premises',
    'free_driveway_parking_on_premises_1_space', 'free_dryer',
    'free_dryer_in_building', 'free_dryer_in_unit', 'free_parking_on_premises',
    'free_street_parking', 'free_washer', 'free_washer_in_building',
    'free_washer_in_unit', 'freezer', 'game_console',
    'game_console_nintendo_switch', 'game_console_ps4', 'game_console_ps5',
    'garden_view', 'gas_stove', 'gym', 'hair_dryer', 'hammock', 'hangers',
    'hdtv', 'hdtv_with_apple_tv', 'hdtv_with_chromecast', 'hdtv_with_netflix',
    'heating', 'heating_split_type_ductless_system', 'high_chair',
    'high_chair_available_upon_request', 'hockey_rink', 'host_greets_you',
    'hot_tub', 'hot_water', 'hot_water_kettle',
    'housekeeping_available_at_extra_cost',
    'housekeeping_available_from_12_00_pm_to_5_00_pm', 'indoor_fireplace',
    'indoor_fireplace_wood_burning', 'induction_stove', 'iron', 'kayak', 'keypad',
    'kitchen', 'kitchenette', 'lake_access', 'lake_view', 'laundromat_nearby',
    'life_size_games', 'lock_on_bedroom_door', 'lockbox',
    'long_term_stays_allowed', 'luggage_dropoff_allowed', 'microwave',
    'miele_induction_stove', 'miele_refrigerator', 'mini_fridge', 'mini_golf',
    'mosquito_net', 'movie_theater', 'noise_decibel_monitors_on_property',
    'other_electric_stove', 'other_induction_stove', 'other_stove',
    'outdoor_dining_area', 'outdoor_furniture', 'outdoor_kitchen',
    'outdoor_playground', 'outdoor_shower', 'outlet_covers', 'oven',
    'pack_n_play_travel_crib', 'pack_n_play_travel_crib_always_at_the_listing',
    'pack_n_play_travel_crib_available_upon_request', 'paid_crib_available_upon_request',
    'paid_dryer_in_building', 'paid_pack_n_play_travel_crib_available_upon_request',
    'paid_parking_garage_off_premises', 'paid_parking_lot_off_premises',
    'paid_parking_lot_on_premises', 'paid_parking_lot_on_premises_1_space',
    'paid_parking_lot_on_premises_2_spaces', 'paid_parking_off_premises',
    'paid_parking_on_premises', 'paid_standalone_high_chair_available_upon_request',
    'paid_street_parking_off_premises', 'paid_washer_in_building',
    'paid_washer_in_unit', 'park_view', 'patio_or_balcony', 'pets_allowed', 'piano',
    'ping_pong_table', 'pocket_wifi', 'pool', 'pool_table', 'pool_view',
    'portable_air_conditioning', 'portable_fans', 'portable_heater',
    'private_backyard', 'private_backyard_fully_fenced',
    'private_backyard_not_fully_fenced', 'private_bbq_grill_charcoal',
    'private_bbq_grill_gas', 'private_entrance', 'private_gym_in_building',
    'private_hot_tub', 'private_living_room', 'private_outdoor_kitchen',
    'private_outdoor_pool_available_seasonally', 'private_patio_or_balcony',
    'private_pool', 'private_sauna', 'radiant_heating', 'record_player',
    'refrigerator', 'resort_access', 'rice_maker', 'room_darkening_shades', 'safe',
    'samsung_refrigerator', 'sauna', 'self_check_in', 'shampoo',
    'shared_backyard', 'shared_backyard_fully_fenced',
    'shared_backyard_not_fully_fenced', 'shared_bbq_grill_charcoal',
    'shared_beach_access', 'shared_beach_access_beachfront',
    'shared_gym_in_building', 'shared_gym_nearby', 'shared_patio_or_balcony',
    'shared_sauna', 'shower_gel', 'siemens_induction_stove', 'siemens_oven',
    'siemens_refrigerator', 'single_level_home', 'single_oven',
    'ski_in_ski_out', 'smart_lock', 'smeg_induction_stove', 'smeg_refrigerator',
    'smeg_stainless_steel_oven', 'smoke_alarm', 'smoking_allowed',
    'sonos_bluetooth_sound_system', 'sonos_sound_system', 'sound_system',
    'sound_system_with_bluetooth_and_aux', 'stainless_steel_double_oven',
    'stainless_steel_electric_stove', 'stainless_steel_induction_stove',
    'stainless_steel_oven', 'stainless_steel_single_oven',
    'standalone_high_chair', 'standalone_high_chair_always_at_the_listing',
    'standalone_high_chair_available_upon_request', 'stove', 'sun_loungers',
    'table_corner_guards', 'toaster', 'trash_compactor', 'tv',
    'tv_with_apple_tv', 'tv_with_chromecast', 'tv_with_netflix',
    'tv_with_standard_cable', 'washer', 'washer_in_building', 'washer_in_unit',
    'waterfront', 'wifi', 'window_ac_unit', 'window_guards', 'wine_glasses',
    'email', 'phone', 'work_email', 'host_location_Amsterdam_Netherlands',
    'host_location_Aspudden_Sweden', 'host_location_Barnvik_Sweden',
    'host_location_Bergsj_Sweden', 'host_location_Enskede_Sweden',
    'host_location_Enskede_rsta_Vant_r_Sweden', 'host_location_Eskilstuna_Sweden',
    'host_location_Falun_Sweden', 'host_location_Goteborg_Sweden',
    'host_location_Gothenburg_Sweden', 'host_location_G_vle_Sweden',
    'host_location_G_teborg_Sweden', 'host_location_Haenertsburg_South_Africa',
    'host_location_Hamburg_Germany', 'host_location_Hammarby_Sweden',
    'host_location_Helsingborg_Sweden', 'host_location_Herf_lge_Denmark',
    'host_location_Hong_Kong', 'host_location_Huddinge_Sweden',
    'host_location_H_sselby_V_llingby_Sweden', 'host_location_India',
    'host_location_J_rf_lla_Sweden', 'host_location_Kampala_Uganda',
    'host_location_Kreuztal_Germany', 'host_location_Link_ping_Sweden',
    'host_location_London_United_Kingdom', 'host_location_Los_Angeles_CA',
    'host_location_Lund_Sweden', 'host_location_Madrid_Spain',
    'host_location_Maglaj_Bosnia_Herzegovina', 'host_location_Malm_Sweden',
    'host_location_Marbella_Spain', 'host_location_Mariefred_Sweden',
    'host_location_Marseille_France', 'host_location_Marshallton_DE',
    'host_location_Milan_Italy', 'host_location_Mississauga_Canada',
    'host_location_Mora_Sweden', 'host_location_Munich_Germany',
    'host_location_M_lnbo_Sweden', 'host_location_Nacka_Sweden',
    'host_location_Nanterre_France', 'host_location_New_York_NY',
    'host_location_Nyk_ping_Sweden', 'host_location_Oslo_Norway',
    'host_location_Palermo_Italy', 'host_location_Reykjav_k_Iceland',
    'host_location_Roanne_France', 'host_location_R_nninge_Sweden',
    'host_location_Saltsj_Duvn_s_Sweden', 'host_location_Sandnes_Norway',
    'host_location_Santa_Ana_El_Salvador', 'host_location_Santa_Monica_CA',
    'host_location_Skarpn_ck_Sweden', 'host_location_Skinnskatteberg_Sweden',
    'host_location_Sk_ne_County_Sweden', 'host_location_Sliema_Malta',
    'host_location_Sollentuna_Sweden', 'host_location_Solna_Sweden',
    'host_location_Sp_nga_Sweden', 'host_location_Stj_rnhov_Sweden',
    'host_location_Stockholm_County_Sweden', 'host_location_Stockholm_Sweden',
    'host_location_Stockholms_l_n_Sweden', 'host_location_Str_msund_Sweden',
    'host_location_Sundbyberg_Sweden', 'host_location_Svedala_Sweden', 'host_location_Sweden',
    'host_location_S_dermanland_County_Sweden', 'host_location_Tyres_Sweden',
    'host_location_Ume_Sweden', 'host_location_United_Kingdom',
    'host_location_Unknown', 'host_location_Uppsala_Sweden',
    'host_location_Varberg_Sweden', 'host_location_Visby_Sweden',
    'host_location_V_rmd_Sweden', 'host_location_V_stra_G_talands_l_n_Sweden',
    'host_location_Z_rich_Switzerland', 'host_location_agesta_Sweden',
    'host_location_lvsj_Sweden', 'host_response_time_a_few_days_or_more',
    'host_response_time_within_a_day', 'host_response_time_within_a_few_hours',
    'host_response_time_within_an_hour',
    'neighbourhood_cleansed_Enskede_rsta_Vant_rs',
    'neighbourhood_cleansed_Farsta', 'neighbourhood_cleansed_H_gersten_Liljeholmens',
    'neighbourhood_cleansed_H_sselby_V_llingby', 'neighbourhood_cleansed_Kungsholmens',
    'neighbourhood_cleansed_Norrmalms', 'neighbourhood_cleansed_Rinkeby_Tensta',
    'neighbourhood_cleansed_Skarpn_cks', 'neighbourhood_cleansed_Sk_rholmens',
    'neighbourhood_cleansed_Sp_nga_Tensta', 'neighbourhood_cleansed_S_dermalms',
    'neighbourhood_cleansed_lvsj', 'neighbourhood_cleansed_stermalms',
    'property_type_Boat', 'property_type_Camper_RV', 'property_type_Entire_cabin',
    'property_type_Entire_condo', 'property_type_Entire_cottage',
    'property_type_Entire_guest_suite', 'property_type_Entire_guesthouse',
    'property_type_Entire_home', 'property_type_Entire_loft',
    'property_type_Entire_rental_unit', 'property_type_Entire_serviced_apartment',
    'property_type_Entire_townhouse', 'property_type_Entire_villa',
    'property_type_Private_room_in_bed_and_breakfast',
    'property_type_Private_room_in_casa_particular',
    'property_type_Private_room_in_condo',
    'property_type_Private_room_in_guest_suite',
    'property_type_Private_room_in_guesthouse',
    'property_type_Private_room_in_home', 'property_type_Private_room_in_hostel',
    'property_type_Private_room_in_loft',
    'property_type_Private_room_in_rental_unit',
    'property_type_Private_room_in_serviced_apartment',
    'property_type_Private_room_in_tiny_home',
    'property_type_Private_room_in_townhouse', 'property_type_Private_room_in_villa',
    'property_type_Room_in_aparthotel', 'property_type_Room_in_boutique_hotel',
    'property_type_Room_in_hostel', 'property_type_Room_in_hotel',
    'property_type_Shared_room_in_condo', 'property_type_Shared_room_in_home',
    'property_type_Shared_room_in_hostel', 'property_type_Tiny_home',
    'room_type_Hotel_room', 'room_type_Private_room', 'room_type_Shared_room'
]

ALL_AMENITIES_TO_DISPLAY = [
    'air_conditioning',
    'arcade_games',
    'baby_bath',
    'baby_monitor',
    'baby_safety_gates',
    'backyard',
    'baking_sheet',
    'barbecue_utensils',
    'bathtub',
    'bay_view',
    'bbq_grill',
    'bbq_grill_charcoal',
    'beach_access_beachfront',
    'beach_essentials',
    'beach_view',
    'bed_linens',
    'bidet',
    'bikes',
    'blender',
    'bluetooth_sound_system',
    'board_games',
    'boat_slip',
    'body_soap',
    'books_and_reading_material',
    'bosch_refrigerator',
    'bread_maker',
    'breakfast',
    'building_staff',
    'canal_view',
    'carbon_monoxide_alarm',
    'ceiling_fan',
    'central_air_conditioning',
    'central_heating',
    'changing_table',
    'children_s_playroom',
    'children_s_bikes',
    'children_s_books_and_toys',
    'children_s_dinnerware',
    'city_skyline_view',
    'cleaning_available_during_stay',
    'cleaning_products',
    'clothing_storage',
    'clothing_storage_closet',
    'clothing_storage_dresser',
    'clothing_storage_walk_in_closet',
    'clothing_storage_wardrobe',
    'coffee',
    'coffee_maker',
    'conditioner',
    'cooking_basics',
    'courtyard_view',
    'crib',
    'dedicated_workspace',
    'dining_table',
    'dishes_and_silverware',
    'dishwasher',
    'double_oven',
    'dove_body_soap',
    'dryer',
    'dryer_in_building',
    'dryer_in_unit',
    'drying_rack_for_clothing',
    'electric_stove',
    'electrolux_induction_stove',
    'electrolux_refrigerator',
    'elevator',
    'essentials',
    'ethernet_connection',
    'ev_charger',
    'ev_charger_level_2',
    'exercise_equipment',
    'exercise_equipment_free_weights',
    'exercise_equipment_yoga_mat',
    'exterior_security_cameras_on_property',
    'extra_pillows_and_blankets',
    'family_fresh_body_soap',
    'fire_extinguisher',
    'fire_pit',
    'fireplace_guards',
    'first_aid_kit',
    'free_driveway_parking_on_premises',
    'free_driveway_parking_on_premises_1_space',
    'free_dryer',
    'free_dryer_in_building',
    'free_dryer_in_unit',
    'free_parking_on_premises',
    'free_street_parking',
    'free_washer',
    'free_washer_in_building',
    'free_washer_in_unit',
    'freezer',
    'game_console',
    'game_console_nintendo_switch',
    'game_console_ps4',
    'game_console_ps5',
    'garden_view',
    'gas_stove',
    'gym',
    'hair_dryer',
    'hammock',
    'hangers',
    'hdtv',
    'hdtv_with_apple_tv',
    'hdtv_with_chromecast',
    'hdtv_with_netflix',
    'heating',
    'heating_split_type_ductless_system',
    'high_chair',
    'high_chair_available_upon_request',
    'hockey_rink',
    'host_greets_you',
    'hot_tub',
    'hot_water',
    'hot_water_kettle',
    'housekeeping_available_at_extra_cost',
    'indoor_fireplace',
    'indoor_fireplace_wood_burning',
    'induction_stove',
    'iron',
    'kayak',
    'keypad',
    'kitchen',
    'kitchenette',
    'lake_access',
    'lake_view',
    'laundromat_nearby',
    'life_size_games',
    'lock_on_bedroom_door',
    'lockbox',
    'long_term_stays_allowed',
    'luggage_dropoff_allowed',
    'microwave',
    'miele_induction_stove',
    'miele_refrigerator',
    'mini_fridge',
    'mini_golf',
    'mosquito_net',
    'movie_theater',
    'noise_decibel_monitors_on_property',
    'other_electric_stove',
    'other_induction_stove',
    'other_stove',
    'outdoor_dining_area',
    'outdoor_furniture',
    'outdoor_kitchen',
    'outdoor_playground',
    'outdoor_shower',
    'outlet_covers',
    'oven',
    'pack_n_play_travel_crib',
    'paid_crib_available_upon_request',
    'paid_dryer_in_building',
    'paid_parking_garage_off_premises',
    'paid_parking_lot_off_premises',
    'paid_parking_lot_on_premises',
    'paid_parking_lot_on_premises_1_space',
    'paid_parking_lot_on_premises_2_spaces',
    'paid_parking_off_premises',
    'paid_parking_on_premises',
    'paid_standalone_high_chair_available_upon_request',
    'paid_street_parking_off_premises',
    'paid_washer_in_building',
    'paid_washer_in_unit',
    'park_view',
    'patio_or_balcony',
    'pets_allowed',
    'piano',
    'ping_pong_table',
    'pocket_wifi',
    'pool',
    'pool_table',
    'pool_view',
    'portable_air_conditioning',
    'portable_fans',
    'portable_heater',
    'private_backyard',
    'private_backyard_fully_fenced',
    'private_backyard_not_fully_fenced',
    'private_bbq_grill_charcoal',
    'private_bbq_grill_gas',
    'private_entrance',
    'private_gym_in_building',
    'private_hot_tub',
    'private_living_room',
    'private_outdoor_kitchen',
    'private_outdoor_pool_available_seasonally',
    'private_patio_or_balcony',
    'private_pool',
    'private_sauna',
    'radiant_heating',
    'record_player',
    'refrigerator',
    'resort_access',
    'rice_maker',
    'room_darkening_shades',
    'safe',
    'samsung_refrigerator',
    'sauna',
    'self_check_in',
    'shampoo',
    'shared_backyard',
    'shared_backyard_fully_fenced',
    'shared_backyard_not_fully_fenced',
    'shared_bbq_grill_charcoal',
    'shared_beach_access',
    'shared_beach_access_beachfront',
    'shared_gym_in_building',
    'shared_gym_nearby',
    'shared_patio_or_balcony',
    'shared_sauna',
    'shower_gel',
    'siemens_induction_stove',
    'siemens_oven',
    'siemens_refrigerator',
    'single_level_home',
    'single_oven',
    'ski_in_ski_out',
    'smart_lock',
    'smeg_induction_stove',
    'smeg_refrigerator',
    'smeg_stainless_steel_oven',
    'smoke_alarm',
    'smoking_allowed',
    'sonos_bluetooth_sound_system',
    'sonos_sound_system',
    'sound_system',
    'sound_system_with_bluetooth_and_aux',
    'stainless_steel_double_oven',
    'stainless_steel_electric_stove',
    'stainless_steel_induction_stove',
    'stainless_steel_oven',
    'stainless_steel_single_oven',
    'standalone_high_chair',
    'standalone_high_chair_always_at_the_listing',
    'standalone_high_chair_available_upon_request',
    'stove',
    'sun_loungers',
    'table_corner_guards',
    'toaster',
    'trash_compactor',
    'tv',
    'tv_with_apple_tv',
    'tv_with_chromecast',
    'tv_with_netflix',
    'tv_with_standard_cable',
    'washer',
    'washer_in_building',
    'washer_in_unit',
    'waterfront',
    'wifi',
    'window_ac_unit',
    'window_guards',
    'wine_glasses',
    # Other specific amenities/features that aren't prefixed but are property characteristics
    'is_shared_bath',
    'instant_bookable',
]